spring.application.name=portfolio.backend

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/portfolio}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Resend API configuration
resend.api-key=${RESEND_API_KEY:}
resend.from-email=${RESEND_FROM_EMAIL:contact@jonathanleite.fr}
resend.to-email=${RESEND_TO_EMAIL:contact@example.com}

# Gemini API configuration
gemini.api-key=${GEMINI_API_KEY:}