INSERT INTO skills (name, category, level) VALUES
('Java', 'Backend', 70),
('PHP (Symfony)', 'Backend', 75),
('SQL (PostgreSQL, MySQL, SQL Server)', 'Backend', 70),
('Python', 'Backend', 20),
('Angular', 'Frontend', 60),
('JavaScript', 'Frontend', 75),
('HTML / CSS', 'Frontend', 75),
('React', 'Frontend', 20),
('Git', 'Outils', 0),
('Docker', 'Outils', 0),
('Maven', 'Outils', 0),
('API REST', 'Outils', 0),
('GitHub', 'Outils', 0),
('JPA', 'Outils', 0),
('Microservices', 'Outils', 0),
('Spring Boot', 'Outils', 0),
('Agile', 'Méthodes', 0),
('Scrum', 'Méthodes', 0),
('Kanban', 'Méthodes', 0),
('MVC', 'Méthodes', 0),
('Design Patterns', 'Méthodes', 0);